### ISSUE TITLE
Using alias directives

### ISSUE THREAD

**Issue by beolutz** [scriptcs-contrib/scriptcs-mef#10]
When using "Using alias directives" like 
**using ResourcesKeys = xy.Common.Properties.ResourcesKeys;**
in combination with multiple scripts it results in an Exception "error CS1529: A using clause must precede all other elements defined in the namespace except extern alias declarations."
Reason is that it seems that all scripts are merged into one file. All r# and using Statements are cut out except using alias directives. Leading to a script file where an using alias directive is in the middle of two classes.

**Comment by laedit** [comment]
Thanks for your report! :smile: 

The only file really [produced](https://github.com/scriptcs-contrib/scriptcs-mef/blob/master/src/ScriptCs.ComponentModel.Composition/ScriptCsCatalog.cs#L459) only write a `#load` line for each script included, and an empty `Marker` class which is used only to get the assembly to load in MEF catalog.

So I think that the issue comes from ScriptCS, maybe a parameter badly used?
Can you reproduce it directly in ScriptCs?
Have you tried to define the `using` inside the class and not before?

**Comment by beolutz** [comment]
There is no problem if directly used in ScriptCS. ScriptCS does not have a problem with using alias directives at all. The problem rises with the merge of multiple files with an using alias directive inside one of them used by the ScriptCSCataloge. 
It really may be a ScriptCS issue by not recognising the alias as an using statement. But I think ScriptCS will not address it because it only occures in combination with the ScriptCSCataloge.

Unfortunatly it seems that ScriptCS also does not allow using statements inside classes. So this would not be a workaround.

Would it be possible to inject the scripts one by one to MEF?

**Comment by laedit** [comment]
Yes, I was thinking at that solution but haven't got the time to study it.
And sadly I don't know when I will have it.

So if you wanna go for a PR, I will gladly accept it :smiley:

**Comment by beolutz** [comment]
#12
